In [6]:
import pandas as pd

In [7]:
laborrates_df = pd.read_csv('../../data/raw/laborrates.csv')
laborrates_df

,LaborRateID,Description,LaborRateCurrencyID,LaborRate,SpecialMeaning,CostCodeID,CostTypeID
0,1,Shop Labor,1,70.35,0,NaN,NaN
1,2,Detailing,1,105.00,1,NaN,NaN
2,3,Erecting,1,84.00,2,NaN,NaN
3,4,Checking,1,133.56,0,NaN,NaN
4,5,VS Blast,1,322.67,0,NaN,NaN
5,7,Voortman System Cost,1,0.00,0,NaN,NaN
6,8,Fabrication Welding,1,70.35,0,NaN,NaN
7,9,Loading - Inbound,1,71.93,0,NaN,NaN
8,12,VS Saw & Drill,1,170.73,0,NaN,NaN
9,13,VS Cope,1,257.46,0,NaN,NaN
10,19,Material Handling - Structural,1,71.93,0,NaN,NaN
11,21,Plate Processing,1,131.25,0,NaN,NaN
12,22,Paint Labor,1,71.93,0,NaN,NaN
13,25,Angle Line,1,143.33,0,NaN,NaN
14,26,PM - shop allocation,1,0.00,0,NaN,NaN
15,27,Camber - Cold,1,149.63,0,NaN,NaN
16,28,Procurement - shop allocation,1,0.00,0,NaN,NaN
17,29,Estimating - shop allocation,1,0.00,0,NaN,NaN
18,32,Press Brake,1,131.25,0,NaN,NaN
19,33,Camber - Hot,1,149.63,0,NaN,NaN
20,34,Tube Plasma,1,94.71,0,NaN,NaN
21,35,Vertical Saw,1,86.84,0,NaN,NaN
22,36,Tube Bender,1,94.71,0,NaN,NaN
23,37,Voortman Paint Line,1,182.18,0,NaN,NaN
24,38,Voortman Paint Line Handling,1,71.93,0,NaN,NaN
25,42,Engineering,1,133.56,0,NaN,NaN

In [8]:
laborrates_df.to_csv('../../data/cleaned/laborrates.csv', index=False)